// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phonueurrfpynmpqldqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBob251ZXVycmZweW5tcHFsZHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTk2NzEsImV4cCI6MjA2NzMzNTY3MX0.jzMz4RSEg1E7X5RNq92mE_LASdxxnOjs2onD2QC5Gm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});